apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    name: demo-pod
    app: demo
spec:
  containers:
    - name: demo-pod-container
      image: andunearc/demo
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          
