name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
        name: build
        env:
          DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
          DOCKER_HUB_KEY: ${{ secret.DOCKER_HUB_KEY }}
          run: |
            ls -l
            echo 'Docker login'
            docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
            echo 'Running build...2
            docker build . -t andunearc/demo:ui-content-latest
            echo 'Pushing image...'
            docker push andunearc/demo:ui-content-latest
            echo 'Done'

